const express = require('express');
const router = express.Router();
const restaurantController = require('../Controller/restaurantController')
const mealController = require('../Controller/mealController')
const signupController=require('../Controller/UserController')
const cityController=require('../Controller/cityController')
const menuController=require('../Controller/menuController')
const orderController=require('../Controller/orderController')
const paymentGatewayController=require('../Controller/paymentGatewayController')
router.get('/restaurantData',restaurantController.getRestaurantData)
router.get('/city',cityController.getCity)
router.get('/restaurantDataByCity',restaurantController.getRestaurantDataByCity)
router.get('/restaurantById/:id',restaurantController.getRestaurantById)
router.post('/restaurantDataByMealType',restaurantController.getRestaurantMealType)
router.get('/restaurantBycity/:city',restaurantController.getRestaurantsByCity)
router.post('/restaurantByCost',restaurantController.getRestaurantsByCost)
router.post('/restaurantBySort',restaurantController.getRestaurantsBySort)
router.get(`/restaurantByPage/:page`,restaurantController.getRestaurantByPage)
router.get('/mealdata',mealController.getmealData)
router.post('/signup',signupController.signUp)
router.post('/login',signupController.login)
router.get('/menu/:id',menuController.getMenu)
router.get('/orderForUser/:username',orderController.getOrdersForUser)
router.post('/saveOrderForUser',orderController.saveOrdersForUser)
router.post('/payment',paymentGatewayController.payment)
router.post('/callback',paymentGatewayController.callback)
module.exports = router;